### ISSUE TITLE
This is a work of art but:

### ISSUE THREAD

**Issue by Githubplay12** [Frayo44/Bypass-Snapchat-SSL-Certificate-Pinning#1]
Do you have any idea where I can disable the root detection, basically all the requests are clear but snapchat still doesn't connect because it detects root (which is essential for frida to be working) so I can't login =/

There's another problem which is the client auth token (which is a whole other story to find how to generate them)

Should I learn arm assembly or javascript or both so I can learn to disable root detection / generate client auth?

For now I just know how to write bots in python.

Thanks sir.

**Comment by Frayo44** [comment]
Hi,
Yes, Snapchat uses [SafetyNet](https://koz.io/inside-safetynet/) to detect if the original state of your phone is changed (rooted, etc).
I would suggest you to try:
1. Using Frida and the script I wrote with a non-rooted phone (Yes, it is possible, read on that).
2. Using some custom ROMs with root access that Snapchat allowed to login. The last time I have tried CyanogenMod, it works.
3. Using Frida with system-less root. 

Both the second and the third option are better, because they don't make us change the APK signature. 

What did you meant by "client auth token", is it the header that is sent in Snapchat's requests?

**Comment by Githubplay12** [comment]
Gotcha about the first point (root bypass).

About the second, yes the "client auth token" in the header is a struggle that very few people bypassed for now (I think only the snaptool team and one guy from a random article that wrote an entire login method) because I think they generate it in the native layer (I'm not sure hence why I'm asking you).

Can frida be used to learn where that come from and learn how to generate one (so I will have to learn javascript only) ? 

Or should I learn ARM assembly as well ? (since it can be generated in the native layer) ? 

Cordially.

**Comment by Frayo44** [comment]
Yes, this header is generated in the native layer (libscplugin.so lib).
Learning ARM asm will help you to understand how this header is build, also Frida can help you. It's up to you, both are always better :)

**Comment by Githubplay12** [comment]
Thank you very much sir, where did you learn when you started ? 

I suppose javascript (for frida) can be learned pretty easily but for ARM asm and ARM reverse engineering I'm struggling to find a good source.

**Comment by Frayo44** [comment]
I suggest you to look at ARM instructions and Snapchat .so files, open a debugger and learn by experience.
Every time you encounter an instruction that you don't understand look for it on the web, I believe that this is the best way.

**Comment by Githubplay12** [comment]
Aiiight, I stop to bother you now.

You helped me a lot thanks.

**Comment by shadowzoom** [comment]
@Githubplay12  hey mate, did you figure it out? I'm trying to intercept snар traffic and can't  even with frida
